In [30]:
import numpy as np

In [31]:
print(np.pi)
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

3.141592653589793
-1.0
1.1
5.2


In [32]:
vec = np.array([1, 2, 3])
print(vec)
mat = np.array([[1, 2, 1], [4, 5, 9], [1, 8, 9]])
print(mat)
print(mat.T)

[1 2 3]
[[1 2 1]
 [4 5 9]
 [1 8 9]]
[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [33]:
vec2 = np.arange(0,15)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
vec3 = np.arange(3, 21, 6)
print(vec3)

[ 3  9 15]


In [35]:
vec4 = np.linspace(0, 5, 10)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [36]:
print(vec4.reshape(5, 2))

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [37]:
rand_mat = np.random.rand(5,5)
print(rand_mat)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [38]:
rand_mat2 = np.random.randn(10,5)
print(rand_mat2)

[[ 0.40042921 -1.08622106 -1.66799137  0.01503144 -1.75928687]
 [-2.14685681  0.5772225  -0.61442201  0.20828418  1.04213175]
 [ 1.20928466 -1.2494457  -0.55420806 -0.01342969 -0.25117138]
 [-0.32698504 -0.72525198 -2.2113319   0.412732    0.22170576]
 [-1.76818167  0.12086385 -0.3587387   0.27825363  0.67020408]
 [-0.73695126  1.14304578 -1.86468352  1.08102033 -0.12538375]
 [-0.51864225  1.10885429 -0.22837289 -0.7176245   1.12932065]
 [ 0.28208676  1.42180097 -0.38022945  0.98470627  0.01263389]
 [ 0.65275889  1.62901515  1.31925366 -0.66145297 -0.86664695]
 [ 0.98294732  1.22239719 -0.13866876 -0.42986292  0.81363253]]


In [39]:
print(np.mean(rand_mat))
print(np.std(rand_mat))

0.5823203847367634
0.23339221827196116


In [40]:
print(np.min(rand_mat2))
print(np.max(rand_mat2))

-2.2113319049289997
1.629015150380305


In [41]:
vec=np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [42]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)
print(vec1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [43]:
np.sqrt(1.44)

1.2

In [44]:
np.cos(np.pi)

-1.0

In [45]:
np.log(6)

1.791759469228055

In [46]:
np.exp(4)

54.598150033144236

In [47]:
arr = np.arange(4, 20, 5)
print(arr)

[ 4  9 14 19]


In [48]:
print(rand_mat)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [49]:
print(rand_mat[1][2])

0.8457695544609282


In [50]:
print(rand_mat[1,2])

0.8457695544609282


In [51]:
print(rand_mat[0:2,1:3])

[[0.25490324 0.3693574 ]
 [0.71010938 0.84576955]]


In [53]:
print(rand_mat[rand_mat > 0])

[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363 0.58199266
 0.71010938 0.84576955 0.34397651 0.89028327 0.75420012 0.63741241
 0.35709262 0.0969524  0.72296819 0.38850257 0.38661374 0.43500235
 0.3279874  0.72003853 0.27726224 0.82142896 0.62826437 0.94215625
 0.91682189]


In [54]:
print(rand_mat)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [55]:
np.save('my_saved_array', rand_mat)

In [61]:
np.savez('my_zipped_array', rand_mat = rand_mat, rand_mat2 = rand_mat)

In [57]:
loaded_vec = np.load('my_saved_array.npy')

In [58]:
loaded_zvec = np.load('my_zipped_array.npz')

In [59]:
print(loaded_vec)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [62]:
print(loaded_zvec)

In [64]:
print(loaded_zvec['rand_mat'])

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [65]:
print(loaded_zvec['rand_mat2'])

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [72]:
np.savetxt('my_text.txt', rand_mat, delimiter = ',')
rand_mat_text = np.loadtxt('my_text.txt', delimiter = ',')
print(rand_mat_text)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]


In [73]:
loaded_array = np.load('my_saved_array.npy')

In [74]:
print(loaded_array)

[[0.76053106 0.25490324 0.3693574  0.72122886 0.66715363]
 [0.58199266 0.71010938 0.84576955 0.34397651 0.89028327]
 [0.75420012 0.63741241 0.35709262 0.0969524  0.72296819]
 [0.38850257 0.38661374 0.43500235 0.3279874  0.72003853]
 [0.27726224 0.82142896 0.62826437 0.94215625 0.91682189]]
