In [1]:
import numpy as np

In [4]:
m1 = np.arange(1000000)
print(m1)

[     0      1      2 ... 999997 999998 999999]


In [11]:
l1 = list(range(99999))

In [12]:
%time for _ in range(10): l2 = l1 = l1 * 2

CPU times: user 846 ms, sys: 490 ms, total: 1.34 s
Wall time: 1.35 s


In [13]:
data = np.random.randn(2, 3)
print(data)

[[ 2.04711292 -0.5547967  -0.36232359]
 [-0.18788428 -0.18291768 -1.31247821]]


In [14]:
data * 10

array([[ 20.47112915,  -5.54796703,  -3.62323594],
       [ -1.87884281,  -1.82917681, -13.12478212]])

In [15]:
data * data

array([[4.19067129, 0.30779938, 0.13127839],
       [0.0353005 , 0.03345888, 1.72259906]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data_1 = [6, 7.5, 8, 0, 1]
print(data_1)

[6, 7.5, 8, 0, 1]


In [21]:
nda_1 = np.array(data_1)
print(nda_1)

[6.  7.5 8.  0.  1. ]


In [22]:
data_2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(data_2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [24]:
nda_2 = np.array(data_2)
print(nda_2)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
nda_2.ndim

2

In [26]:
nda_2.shape

(2, 4)

In [27]:
nda_2.dtype

dtype('int64')

In [28]:
int_array = np.arange(10)
print(int_array)

[0 1 2 3 4 5 6 7 8 9]
