# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [8]:
# we can create numpy arrays by converting lists
# this is a vector
my_list = [1, 2, 3]
print(my_list)
print(type(my_list))
vec = np.array(my_list)
print(vec)
print(type(vec))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [7]:
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [9]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15) # starting with 0, before 15
print(vec2)
print('')
vec3 = np.arange(3,21,6) # start with 3 and less than 21 step 6
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [11]:
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [12]:
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [13]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [15]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [16]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [18]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [19]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.37378375 0.54643303 0.83173697 0.57442019 0.04530177]
 [0.52699476 0.97451549 0.15291663 0.32216005 0.80140103]
 [0.42013681 0.662491   0.46912392 0.47723738 0.16043219]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]

[[ 0.29604451 -0.99932117  0.23155317  0.83745837  1.50994384]
 [-1.85635681 -1.29012069  0.92095488 -0.01979016  0.04812739]
 [ 0.06877472  0.15608366  1.17935264  1.18314537 -2.06142545]
 [-1.1631392  -0.25818279  0.00489131  2.06436235  1.2300535 ]
 [-0.41839117 -0.02567631 -0.78871946  0.12302715  0.74353665]
 [ 0.44003707 -0.63469386  0.39565933  0.27365235 -0.39506332]
 [-0.71212527 -0.37217352  1.44398927  0.44735779  0.82393001]
 [ 0.03699826  0.91771705  0.39929985  2.19162002 -0.702546  ]
 [ 1.05274678 -1.34521582  0.55336533  0.47935947  0.07190995]
 [ 0.08168703  0.59756657 -1.4045234   0.11120744 -2.60823864]]


In [20]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5074388355403043
0.9891214546191432


In [21]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.04530177396635637
2.1916200242044925


In [ ]:
# break here for next video!

In [22]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.39576491 -0.54790645  0.51618791 -0.27085733  0.22835427  0.83802794
  0.90002513 -0.41817633  0.47633226 -0.22890796 -1.40948806 -0.90889343
  0.27369186 -0.54166042  0.21589238 -1.28889801  2.60590694  0.41381561
 -0.97990232]
0.9000251331054896


In [23]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.22835427  0.83802794  0.90002513 -0.41817633  0.47633226]


In [24]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.39576491 -0.27085733  0.90002513 -0.22890796  0.27369186]


In [25]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.37378375 0.54643303 0.83173697 0.57442019 0.04530177]
 [0.52699476 0.97451549 0.15291663 0.32216005 0.80140103]
 [0.42013681 0.662491   0.46912392 0.47723738 0.16043219]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]
0.15291663260806265
0.15291663260806265


In [26]:
print(rand_mat[0:2,1:3])

[[0.54643303 0.83173697]
 [0.97451549 0.15291663]]


In [27]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.39576491 -0.54790645  0.51618791 -0.27085733  0.22835427  0.83802794
  0.90002513 -0.41817633  0.47633226 -0.22890796 -1.40948806 -0.90889343
  0.27369186 -0.54166042  0.21589238 -1.28889801  2.60590694  0.41381561
 -0.97990232]

[-0.39576491 -0.54790645  0.51618791  4.          4.          0.83802794
  0.90002513 -0.41817633  0.47633226 -0.22890796 -1.40948806 -0.90889343
  0.27369186 -0.54166042  0.21589238 -1.28889801  2.60590694  0.41381561
 -0.97990232]

[-0.39576491 -0.54790645  0.51618791  1.          2.          0.83802794
  0.90002513 -0.41817633  0.47633226 -0.22890796 -1.40948806 -0.90889343
  0.27369186 -0.54166042  0.21589238 -1.28889801  2.60590694  0.41381561
 -0.97990232]


In [28]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.37378375 0.54643303 0.83173697 0.57442019 0.04530177]
 [0.52699476 0.97451549 0.15291663 0.32216005 0.80140103]
 [0.42013681 0.662491   0.46912392 0.47723738 0.16043219]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]

[[0.37378375 0.54643303 0.83173697 0.57442019 0.04530177]
 [0.52699476 0.97451549 0.15291663 0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]


In [29]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.37378375 0.54643303 0.83173697]
 [0.52699476 0.97451549 0.15291663]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [30]:
print(rand_mat)

[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.         3.         0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]


In [31]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.         3.         0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]


In [ ]:
# break here for next video

In [32]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.52629321 -0.00637952  0.65357611  0.09829406  1.6950902  -0.94988915
 -0.4853943  -1.72862927 -0.45000071  0.48136838  0.10378655 -0.97919705
 -1.87154317 -0.49366721 -0.71662608]
[ True False  True  True  True False False False False  True  True False
 False False False]
[0.52629321 0.65357611 0.09829406 1.6950902  0.48136838 0.10378655]


In [33]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.29604451 -0.99932117  0.23155317  0.83745837  1.50994384]
 [-1.85635681 -1.29012069  0.92095488 -0.01979016  0.04812739]
 [ 0.06877472  0.15608366  1.17935264  1.18314537 -2.06142545]
 [-1.1631392  -0.25818279  0.00489131  2.06436235  1.2300535 ]
 [-0.41839117 -0.02567631 -0.78871946  0.12302715  0.74353665]
 [ 0.44003707 -0.63469386  0.39565933  0.27365235 -0.39506332]
 [-0.71212527 -0.37217352  1.44398927  0.44735779  0.82393001]
 [ 0.03699826  0.91771705  0.39929985  2.19162002 -0.702546  ]
 [ 1.05274678 -1.34521582  0.55336533  0.47935947  0.07190995]
 [ 0.08168703  0.59756657 -1.4045234   0.11120744 -2.60823864]]
[0.29604451 0.23155317 0.83745837 1.50994384 0.92095488 0.04812739
 0.06877472 0.15608366 1.17935264 1.18314537 0.00489131 2.06436235
 1.2300535  0.12302715 0.74353665 0.44003707 0.39565933 0.27365235
 1.44398927 0.44735779 0.82393001 0.03699826 0.91771705 0.39929985
 2.19162002 1.05274678 0.55336533 0.47935947 0.07190995 0.08168703
 0.59756657 0.11120744]


In [34]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[ 0.52629321 -0.00637952  0.65357611  0.09829406  1.6950902  -0.94988915
 -0.4853943  -1.72862927 -0.45000071  0.48136838  0.10378655 -0.97919705
 -1.87154317 -0.49366721 -0.71662608]

[-5.         -0.00637952 -5.          0.09829406 -5.         -0.94988915
 -0.4853943  -1.72862927 -0.45000071  0.48136838  0.10378655 -0.97919705
 -1.87154317 -0.49366721 -0.71662608]


In [35]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [36]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [37]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.29604451 -0.99932117  0.23155317  0.83745837  1.50994384]
 [-1.85635681 -1.29012069  0.92095488 -0.01979016  0.04812739]
 [ 0.06877472  0.15608366  1.17935264  1.18314537 -2.06142545]
 [-1.1631392  -0.25818279  0.00489131  2.06436235  1.2300535 ]
 [-0.41839117 -0.02567631 -0.78871946  0.12302715  0.74353665]
 [ 0.44003707 -0.63469386  0.39565933  0.27365235 -0.39506332]
 [-0.71212527 -0.37217352  1.44398927  0.44735779  0.82393001]
 [ 0.03699826  0.91771705  0.39929985  2.19162002 -0.702546  ]
 [ 1.05274678 -1.34521582  0.55336533  0.47935947  0.07190995]
 [ 0.08168703  0.59756657 -1.4045234   0.11120744 -2.60823864]]



In [38]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.         3.         0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]

[[ 0.29604451 -0.99932117  0.23155317  0.83745837  1.50994384]
 [-1.85635681 -1.29012069  0.92095488 -0.01979016  0.04812739]
 [ 0.06877472  0.15608366  1.17935264  1.18314537 -2.06142545]
 [-1.1631392  -0.25818279  0.00489131  2.06436235  1.2300535 ]
 [-0.41839117 -0.02567631 -0.78871946  0.12302715  0.74353665]
 [ 0.44003707 -0.63469386  0.39565933  0.27365235 -0.39506332]
 [-0.71212527 -0.37217352  1.44398927  0.44735779  0.82393001]
 [ 0.03699826  0.91771705  0.39929985  2.19162002 -0.702546  ]
 [ 1.05274678 -1.34521582  0.55336533  0.47935947  0.07190995]
 [ 0.08168703  0.59756657 -1.4045234   0.11120744 -2.60823864]]
[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.    

In [39]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.         3.         0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]

[[3.         3.         3.         0.57442019 0.04530177]
 [3.         3.         3.         0.         0.        ]
 [0.42013681 0.662491   0.46912392 0.         0.        ]
 [0.15000766 0.93110941 0.18736583 0.13503357 0.68428438]
 [0.44106534 0.72567183 0.72881317 0.7879669  0.57556784]]
