In [40]:
import numpy as np
import pandas as pd

In [2]:
l1 = [1, 2, 3, 4, 5]
l2 = (1, 2, 3, 4, 5)
print(type(l1))
print(l1)
print(type(l2))
print(l2)

<class 'list'>
[1, 2, 3, 4, 5]
<class 'tuple'>
(1, 2, 3, 4, 5)


In [3]:
s1 = pd.Series(l1)
s2 = pd.Series(l2)
print(s1)
print(s2)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [5]:
print(s1.values)
print(s2.values)

[1 2 3 4 5]
[1 2 3 4 5]


In [6]:
print(s1.index)
print(s2.index)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)


In [7]:
i1 = ['a', 'b', 'c', 'd', 'e']
print(i1)

['a', 'b', 'c', 'd', 'e']


In [8]:
s3 = pd.Series(l1, index = i1)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [20]:
print(s3['a'])

1


In [21]:
s3[s3 > 2]

c    3
d    4
e    5
dtype: int64

In [9]:
s4 = s3 * s3
print(s4)

a     1
b     4
c     9
d    16
e    25
dtype: int64


In [13]:
print('b' in s3)
s3['b']

True


2

In [15]:
sdata = {'Ohio': 3500, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
print(sdata)
print(sdata['Ohio'])

{'Ohio': 3500, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
3500


In [17]:
s4 = pd.Series(sdata)
print(s4)
print(s4['Texas'])

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
71000


In [18]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
s5 = pd.Series(sdata, index = states)
print(s5)

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [19]:
pd.isnull(s5)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
s5.name = 'population'
s5.index.name = 'State'
print(s5)

State
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [21]:
print(s5[:3])

State
California        NaN
Ohio           3500.0
Oregon        16000.0
Name: population, dtype: float64


In [22]:
s5

State
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [24]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [26]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [27]:
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [28]:
frame['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [29]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [31]:
frame.loc[2]

state    Ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [32]:

frame.debt = 16.5
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2


In [33]:
frame_2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'], index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [34]:
print(frame_2.head())

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN


In [35]:
frame_2.debt = 16.5
frame_2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [36]:
frame_2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame_2.debt = np.arange(6.)
frame_2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [42]:
frame_2['eastern'] = frame_2.state == 'Ohio'
frame_2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   0.0     True
two    2001    Ohio  1.7   1.0     True
three  2002    Ohio  3.6   2.0     True
four   2001  Nevada  2.4   3.0    False
five   2002  Nevada  2.9   4.0    False
six    2003  Nevada  3.2   5.0    False

In [43]:
del frame_2['eastern']
frame_2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [44]:
pop = {'Navada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [45]:
frame_3 = pd.DataFrame(pop)

In [46]:
frame_3

Navada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [47]:
frame_3.isnull()

Navada   Ohio
2001   False  False
2002   False  False
2000    True  False

In [48]:
frame_3.T

2001  2002  2000
Navada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [51]:
frame_3.index.name = 'year'
frame_3.columns.name = 'state'

In [52]:
frame_3

state  Navada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [53]:
frame_3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [54]:
'Ohio' in frame_3.columns

True

In [55]:
2003 in frame_3.index

False

In [56]:
frame_3.sum

<bound method DataFrame.sum of state  Navada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5>

In [57]:
frame_3.sum(axis = 'columns')

year
2001    4.1
2002    6.5
2000    1.5
dtype: float64

In [63]:
frame_3.idxmax()

state
Navada    2002
Ohio      2002
dtype: int64

In [62]:
frame_3.cumsum()

state  Navada  Ohio
year               
2001      2.4   1.7
2002      5.3   5.3
2000      NaN   6.8

In [61]:
frame_3.describe()

state    Navada      Ohio
count  2.000000  3.000000
mean   2.650000  2.266667
std    0.353553  1.159023
min    2.400000  1.500000
25%    2.525000  1.600000
50%    2.650000  1.700000
75%    2.775000  2.650000
max    2.900000  3.600000