In [12]:
import numpy as np
import pandas as pd
demo_array = np.arange(0,10) 
print(demo_array)
print(demo_array <3)
print(demo_array[demo_array <6])
print(np.max(demo_array))

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True False False False False False False False]
[0 1 2 3 4 5]
9


In [4]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [5]:
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [6]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

In [7]:
test_array[2:3]

[12]

In [8]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [9]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [10]:
score = [10, 15, 20, 25]

In [13]:
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [14]:
newcolumn =  ["A", "B", "C", "D", "E"]

In [15]:
pd.DataFrame('Alphabets') = newcolumn

SyntaxError: can't assign to function call (<ipython-input-15-cc5fed05d1f8>, line 1)

In [16]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [17]:
demo_array = np.arange(10,21)

subset_demo_array = demo_array[0:7]

subset_demo_array[:]= 101

subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [18]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])

flowers['daisy']

5

In [19]:
s1 = pd.Series(['a', 'b'])

s2 = pd.Series(['c', 'd'])

In [20]:
pd.concat([s1+ s2])

0    ac
1    bd
dtype: object

In [21]:
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

In [22]:
football = [24, 235, 34, 456, 65, 67]
type(football)

list

In [23]:
npa = np.array(football)
type(npa)

numpy.ndarray